{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "886e0a8d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<Response [200]>\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import random\n",
    "import pandas as pd\n",
    "from bs4 import BeautifulSoup\n",
    "import csv\n",
    "import re\n",
    "\n",
    "url = \"https://www.allrecipes.com/recipes/455/everyday-cooking/more-meal-ideas/30-minute-meals/\"\n",
    "user_agents_list = [\n",
    "    'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',\n",
    "    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36',\n",
    "    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36'\n",
    "]\n",
    "\n",
    "response = requests.get(url, headers={'User-Agent': random.choice(user_agents_list)})\n",
    "print(response)\n",
    "soup = BeautifulSoup(response.text, \"html.parser\")\n",
    "# print(soup)\n",
    "jobs = []\n",
    "\n",
    "for job in soup.find_all(\"a\", {\"class\": \"comp mntl-card-list-items mntl-document-card mntl-card card card--no-image\"}):\n",
    "#     print(job)\n",
    "    \n",
    "    Dish_name = job.find(\"span\", {\"class\": \"card__title-text\"}).text.strip()\n",
    "    Link = job.get('href')\n",
    "    \n",
    "    jobs.append({\"Dish Name\": Dish_name, \"Link\": Link})\n",
    "\n",
    "\n",
    "# # print(jobs)\n",
    "jobs_df = pd.DataFrame(jobs)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "b9b7ed54",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Dish Name</th>\n",
       "      <th>Link</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Quick Beef Stir-Fry</td>\n",
       "      <td>https://www.allrecipes.com/recipe/228823/quick...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Pesto Pasta</td>\n",
       "      <td>https://www.allrecipes.com/recipe/11887/pesto-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Spicy Thai Basil Chicken (Pad Krapow Gai)</td>\n",
       "      <td>https://www.allrecipes.com/recipe/257938/spicy...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Chicken Katsu</td>\n",
       "      <td>https://www.allrecipes.com/recipe/72068/chicke...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Simple Beef Stroganoff</td>\n",
       "      <td>https://www.allrecipes.com/recipe/16311/simple...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Chicken Marsala</td>\n",
       "      <td>https://www.allrecipes.com/recipe/8887/chicken...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Pan-Seared Tilapia</td>\n",
       "      <td>https://www.allrecipes.com/recipe/201934/pan-s...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Easy Tuna Patties</td>\n",
       "      <td>https://www.allrecipes.com/recipe/230857/easy-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Easy Garlic-Lemon Scallops</td>\n",
       "      <td>https://www.allrecipes.com/recipe/132358/easy-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Black Beans and Rice</td>\n",
       "      <td>https://www.allrecipes.com/recipe/15559/black-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Creamed Chipped Beef on Toast</td>\n",
       "      <td>https://www.allrecipes.com/recipe/20225/creame...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Buttered Noodles</td>\n",
       "      <td>https://www.allrecipes.com/recipe/244458/butte...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Southern Fried Catfish</td>\n",
       "      <td>https://www.allrecipes.com/recipe/140930/south...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Air Fryer Chicken Thighs</td>\n",
       "      <td>https://www.allrecipes.com/recipe/272858/air-f...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Simple Broiled Haddock</td>\n",
       "      <td>https://www.allrecipes.com/recipe/232906/simpl...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Easy Lasagna</td>\n",
       "      <td>https://www.allrecipes.com/recipe/12011/easy-l...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Fish in Foil</td>\n",
       "      <td>https://www.allrecipes.com/recipe/21306/fish-i...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Creamy Garlic Pasta</td>\n",
       "      <td>https://www.allrecipes.com/recipe/269500/cream...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Simple Garlic Shrimp</td>\n",
       "      <td>https://www.allrecipes.com/recipe/220597/simpl...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Pesto Pasta with Chicken</td>\n",
       "      <td>https://www.allrecipes.com/recipe/46982/pesto-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Blackened Chicken</td>\n",
       "      <td>https://www.allrecipes.com/recipe/8571/blacken...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Linguine with Clam Sauce</td>\n",
       "      <td>https://www.allrecipes.com/recipe/11951/lingui...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Baked Haddock</td>\n",
       "      <td>https://www.allrecipes.com/recipe/100195/baked...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>Honey Glazed Chicken</td>\n",
       "      <td>https://www.allrecipes.com/recipe/231939/honey...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Sweet and Sour Meatballs</td>\n",
       "      <td>https://www.allrecipes.com/recipe/16305/sweet-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Honey Walnut Shrimp</td>\n",
       "      <td>https://www.allrecipes.com/recipe/93234/honey-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Sirloin Steak with Garlic Butter</td>\n",
       "      <td>https://www.allrecipes.com/recipe/14554/sirloi...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Chicago-Style Hot Dog</td>\n",
       "      <td>https://www.allrecipes.com/recipe/134483/chica...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Easy 5-Ingredient Salmon</td>\n",
       "      <td>https://www.allrecipes.com/recipe/189058/super...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>Spicy Grilled Shrimp</td>\n",
       "      <td>https://www.allrecipes.com/recipe/12775/spicy-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>Baked Fresh Rainbow Trout</td>\n",
       "      <td>https://www.allrecipes.com/recipe/236814/baked...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>Crab Legs with Garlic Butter Sauce</td>\n",
       "      <td>https://www.allrecipes.com/recipe/155375/crab-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>Baked Chicken Schnitzel</td>\n",
       "      <td>https://www.allrecipes.com/recipe/244950/baked...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>Heavenly Halibut</td>\n",
       "      <td>https://www.allrecipes.com/recipe/76659/heaven...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>Baked Flounder with Panko and Parmesan</td>\n",
       "      <td>https://www.allrecipes.com/recipe/231549/baked...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>Classic Cuban-Style Picadillo</td>\n",
       "      <td>https://www.allrecipes.com/recipe/220164/class...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>Crispy Panko Chicken Breasts</td>\n",
       "      <td>https://www.allrecipes.com/recipe/239428/crisp...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>Best Ever Crab Cakes</td>\n",
       "      <td>https://www.allrecipes.com/recipe/82347/best-e...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>Baby Spinach Omelet</td>\n",
       "      <td>https://www.allrecipes.com/recipe/69471/baby-s...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>Quick and Easy Chicken Spaghetti</td>\n",
       "      <td>https://www.allrecipes.com/recipe/26286/quick-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>Baked Salmon Fillets Dijon</td>\n",
       "      <td>https://www.allrecipes.com/recipe/22538/baked-...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>Scrumptious Salmon Cakes</td>\n",
       "      <td>https://www.allrecipes.com/recipe/240130/scrum...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>Super Easy Chicken and Dumplings</td>\n",
       "      <td>https://www.allrecipes.com/recipe/218562/super...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>Sesame-Seared Tuna</td>\n",
       "      <td>https://www.allrecipes.com/recipe/71698/sesame...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>Parmesan Crusted Tilapia Fillets</td>\n",
       "      <td>https://www.allrecipes.com/recipe/228056/parme...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>Blackened Fish</td>\n",
       "      <td>https://www.allrecipes.com/recipe/38028/blacke...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>Savory Sea Scallops and Angel Hair Pasta</td>\n",
       "      <td>https://www.allrecipes.com/recipe/216757/savor...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>Japanese-Style Deep-Fried Shrimp</td>\n",
       "      <td>https://www.allrecipes.com/recipe/127500/japan...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>Quick Chicken Piccata</td>\n",
       "      <td>https://www.allrecipes.com/recipe/220751/quick...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>Beer Batter Fish Made Great</td>\n",
       "      <td>https://www.allrecipes.com/recipe/20107/beer-b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>Air Fryer Tilapia with Fresh Lemon Pepper</td>\n",
       "      <td>https://www.allrecipes.com/recipe/280935/air-f...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>Blackened Salmon Fillets</td>\n",
       "      <td>https://www.allrecipes.com/recipe/36487/blacke...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>52</th>\n",
       "      <td>Air Fryer Lobster Tails with Lemon-Garlic Butter</td>\n",
       "      <td>https://www.allrecipes.com/recipe/276006/air-f...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>53</th>\n",
       "      <td>Parmesan Crusted Chicken</td>\n",
       "      <td>https://www.allrecipes.com/recipe/219431/parme...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>54</th>\n",
       "      <td>Baked Fish Fillets</td>\n",
       "      <td>https://www.allrecipes.com/recipe/256349/baked...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>55</th>\n",
       "      <td>Crumbed Chicken Tenderloins (Air Fried)</td>\n",
       "      <td>https://www.allrecipes.com/recipe/260625/crumb...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>56</th>\n",
       "      <td>Old Bay-Seasoned Steamed Shrimp</td>\n",
       "      <td>https://www.allrecipes.com/recipe/279463/old-b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>57</th>\n",
       "      <td>Shrimp Egg Foo Young</td>\n",
       "      <td>https://www.allrecipes.com/recipe/163370/shrim...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>58</th>\n",
       "      <td>Crispy Baked Walleye</td>\n",
       "      <td>https://www.allrecipes.com/recipe/217339/crisp...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>59</th>\n",
       "      <td>Shrimp Scampi</td>\n",
       "      <td>https://www.allrecipes.com/recipe/19508/shrimp...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                           Dish Name  \\\n",
       "0                                Quick Beef Stir-Fry   \n",
       "1                                        Pesto Pasta   \n",
       "2          Spicy Thai Basil Chicken (Pad Krapow Gai)   \n",
       "3                                      Chicken Katsu   \n",
       "4                             Simple Beef Stroganoff   \n",
       "5                                    Chicken Marsala   \n",
       "6                                 Pan-Seared Tilapia   \n",
       "7                                  Easy Tuna Patties   \n",
       "8                         Easy Garlic-Lemon Scallops   \n",
       "9                               Black Beans and Rice   \n",
       "10                     Creamed Chipped Beef on Toast   \n",
       "11                                  Buttered Noodles   \n",
       "12                            Southern Fried Catfish   \n",
       "13                          Air Fryer Chicken Thighs   \n",
       "14                            Simple Broiled Haddock   \n",
       "15                                      Easy Lasagna   \n",
       "16                                      Fish in Foil   \n",
       "17                               Creamy Garlic Pasta   \n",
       "18                              Simple Garlic Shrimp   \n",
       "19                          Pesto Pasta with Chicken   \n",
       "20                                 Blackened Chicken   \n",
       "21                          Linguine with Clam Sauce   \n",
       "22                                     Baked Haddock   \n",
       "23                              Honey Glazed Chicken   \n",
       "24                          Sweet and Sour Meatballs   \n",
       "25                               Honey Walnut Shrimp   \n",
       "26                  Sirloin Steak with Garlic Butter   \n",
       "27                             Chicago-Style Hot Dog   \n",
       "28                          Easy 5-Ingredient Salmon   \n",
       "29                              Spicy Grilled Shrimp   \n",
       "30                         Baked Fresh Rainbow Trout   \n",
       "31                Crab Legs with Garlic Butter Sauce   \n",
       "32                           Baked Chicken Schnitzel   \n",
       "33                                  Heavenly Halibut   \n",
       "34            Baked Flounder with Panko and Parmesan   \n",
       "35                     Classic Cuban-Style Picadillo   \n",
       "36                      Crispy Panko Chicken Breasts   \n",
       "37                              Best Ever Crab Cakes   \n",
       "38                               Baby Spinach Omelet   \n",
       "39                  Quick and Easy Chicken Spaghetti   \n",
       "40                        Baked Salmon Fillets Dijon   \n",
       "41                          Scrumptious Salmon Cakes   \n",
       "42                  Super Easy Chicken and Dumplings   \n",
       "43                                Sesame-Seared Tuna   \n",
       "44                  Parmesan Crusted Tilapia Fillets   \n",
       "45                                    Blackened Fish   \n",
       "46          Savory Sea Scallops and Angel Hair Pasta   \n",
       "47                  Japanese-Style Deep-Fried Shrimp   \n",
       "48                             Quick Chicken Piccata   \n",
       "49                       Beer Batter Fish Made Great   \n",
       "50         Air Fryer Tilapia with Fresh Lemon Pepper   \n",
       "51                          Blackened Salmon Fillets   \n",
       "52  Air Fryer Lobster Tails with Lemon-Garlic Butter   \n",
       "53                          Parmesan Crusted Chicken   \n",
       "54                                Baked Fish Fillets   \n",
       "55           Crumbed Chicken Tenderloins (Air Fried)   \n",
       "56                   Old Bay-Seasoned Steamed Shrimp   \n",
       "57                              Shrimp Egg Foo Young   \n",
       "58                              Crispy Baked Walleye   \n",
       "59                                     Shrimp Scampi   \n",
       "\n",
       "                                                 Link  \n",
       "0   https://www.allrecipes.com/recipe/228823/quick...  \n",
       "1   https://www.allrecipes.com/recipe/11887/pesto-...  \n",
       "2   https://www.allrecipes.com/recipe/257938/spicy...  \n",
       "3   https://www.allrecipes.com/recipe/72068/chicke...  \n",
       "4   https://www.allrecipes.com/recipe/16311/simple...  \n",
       "5   https://www.allrecipes.com/recipe/8887/chicken...  \n",
       "6   https://www.allrecipes.com/recipe/201934/pan-s...  \n",
       "7   https://www.allrecipes.com/recipe/230857/easy-...  \n",
       "8   https://www.allrecipes.com/recipe/132358/easy-...  \n",
       "9   https://www.allrecipes.com/recipe/15559/black-...  \n",
       "10  https://www.allrecipes.com/recipe/20225/creame...  \n",
       "11  https://www.allrecipes.com/recipe/244458/butte...  \n",
       "12  https://www.allrecipes.com/recipe/140930/south...  \n",
       "13  https://www.allrecipes.com/recipe/272858/air-f...  \n",
       "14  https://www.allrecipes.com/recipe/232906/simpl...  \n",
       "15  https://www.allrecipes.com/recipe/12011/easy-l...  \n",
       "16  https://www.allrecipes.com/recipe/21306/fish-i...  \n",
       "17  https://www.allrecipes.com/recipe/269500/cream...  \n",
       "18  https://www.allrecipes.com/recipe/220597/simpl...  \n",
       "19  https://www.allrecipes.com/recipe/46982/pesto-...  \n",
       "20  https://www.allrecipes.com/recipe/8571/blacken...  \n",
       "21  https://www.allrecipes.com/recipe/11951/lingui...  \n",
       "22  https://www.allrecipes.com/recipe/100195/baked...  \n",
       "23  https://www.allrecipes.com/recipe/231939/honey...  \n",
       "24  https://www.allrecipes.com/recipe/16305/sweet-...  \n",
       "25  https://www.allrecipes.com/recipe/93234/honey-...  \n",
       "26  https://www.allrecipes.com/recipe/14554/sirloi...  \n",
       "27  https://www.allrecipes.com/recipe/134483/chica...  \n",
       "28  https://www.allrecipes.com/recipe/189058/super...  \n",
       "29  https://www.allrecipes.com/recipe/12775/spicy-...  \n",
       "30  https://www.allrecipes.com/recipe/236814/baked...  \n",
       "31  https://www.allrecipes.com/recipe/155375/crab-...  \n",
       "32  https://www.allrecipes.com/recipe/244950/baked...  \n",
       "33  https://www.allrecipes.com/recipe/76659/heaven...  \n",
       "34  https://www.allrecipes.com/recipe/231549/baked...  \n",
       "35  https://www.allrecipes.com/recipe/220164/class...  \n",
       "36  https://www.allrecipes.com/recipe/239428/crisp...  \n",
       "37  https://www.allrecipes.com/recipe/82347/best-e...  \n",
       "38  https://www.allrecipes.com/recipe/69471/baby-s...  \n",
       "39  https://www.allrecipes.com/recipe/26286/quick-...  \n",
       "40  https://www.allrecipes.com/recipe/22538/baked-...  \n",
       "41  https://www.allrecipes.com/recipe/240130/scrum...  \n",
       "42  https://www.allrecipes.com/recipe/218562/super...  \n",
       "43  https://www.allrecipes.com/recipe/71698/sesame...  \n",
       "44  https://www.allrecipes.com/recipe/228056/parme...  \n",
       "45  https://www.allrecipes.com/recipe/38028/blacke...  \n",
       "46  https://www.allrecipes.com/recipe/216757/savor...  \n",
       "47  https://www.allrecipes.com/recipe/127500/japan...  \n",
       "48  https://www.allrecipes.com/recipe/220751/quick...  \n",
       "49  https://www.allrecipes.com/recipe/20107/beer-b...  \n",
       "50  https://www.allrecipes.com/recipe/280935/air-f...  \n",
       "51  https://www.allrecipes.com/recipe/36487/blacke...  \n",
       "52  https://www.allrecipes.com/recipe/276006/air-f...  \n",
       "53  https://www.allrecipes.com/recipe/219431/parme...  \n",
       "54  https://www.allrecipes.com/recipe/256349/baked...  \n",
       "55  https://www.allrecipes.com/recipe/260625/crumb...  \n",
       "56  https://www.allrecipes.com/recipe/279463/old-b...  \n",
       "57  https://www.allrecipes.com/recipe/163370/shrim...  \n",
       "58  https://www.allrecipes.com/recipe/217339/crisp...  \n",
       "59  https://www.allrecipes.com/recipe/19508/shrimp...  "
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "jobs_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "d8f30121",
   "metadata": {},
   "outputs": [],
   "source": [
    "jobs_df.to_csv(\"recipe.csv\", encoding='utf-8', index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36c632a1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aad2a2ca",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d532a4d3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
